(function(){
  const root=root_element.querySelector('#ledger-report-dashboard');if(!root)return;
  const $=s=>root.querySelector(s),fmt=n=>Number(n||0).toLocaleString(undefined,{minimumFractionDigits:2,maximumFractionDigits:2});
  let companyControl=null,accountControl=null,partyControl=null;
  function esc(v){return frappe.utils.escape_html(String(v||''))}
  function iso(d){return d.getFullYear()+'-'+String(d.getMonth()+1).padStart(2,'0')+'-'+String(d.getDate()).padStart(2,'0')}
  function amount(v){return Number(v||0)?fmt(v):'<span class="lrd-zero">—</span>'}
  function makeLink(parent,doctype,placeholder){return frappe.ui.form.make_control({parent:window.jQuery(parent),df:{fieldtype:'Link',options:doctype,placeholder:placeholder},render_input:true})}
  function userCompany(){return (frappe.defaults&&frappe.defaults.get_user_default&&frappe.defaults.get_user_default('company'))||(frappe.boot&&frappe.boot.sysdefaults&&frappe.boot.sysdefaults.company)||''}
  function cleanPartyDropdown(){const partyType=$('#lrd-party-type').value;if(partyType!=='Customer'&&partyType!=='Supplier')return;root.querySelectorAll('#lrd-party-control .awesomplete ul li').forEach(function(li){const strong=li.querySelector('strong'),value=(li.getAttribute('data-value')||(strong&&strong.textContent)||li.textContent||'').split('\\n')[0].trim();li.innerHTML='<strong>'+esc(value)+'</strong>'})}
  function makePartyLink(){const mount=$('#lrd-party-control');mount.innerHTML='';partyControl=makeLink(mount,$('#lrd-party-type').value||'Customer','Search '+($('#lrd-party-type').value||'Party'));const input=mount.querySelector('input');if(input){input.addEventListener('input',function(){setTimeout(cleanPartyDropdown,80);setTimeout(cleanPartyDropdown,200);setTimeout(cleanPartyDropdown,500)});input.addEventListener('focus',function(){setTimeout(cleanPartyDropdown,80);setTimeout(cleanPartyDropdown,250)})}}
  function params(){return new URLSearchParams(window.location.search||'')}
  function defaults(){const qs=params(),now=new Date(),from=new Date(now.getFullYear(),now.getMonth(),1);$('#lrd-from').value=qs.get('from_date')||iso(from);$('#lrd-to').value=qs.get('to_date')||iso(now);if(qs.get('party_type'))$('#lrd-party-type').value=qs.get('party_type')}
  function render(data){
    const rows=data.rows||[],table=$('#lrd-table'),opening=Number(data.opening_balance||0);let balance=opening,totalDebit=0,totalCredit=0;
    const openingRow='<tr class="lrd-opening"><td>'+esc($('#lrd-from').value)+'</td><td>Opening</td><td></td><td>Opening Balance</td><td></td><td></td><td>'+fmt(opening)+'</td></tr>';
    const body=rows.map(r=>{const debit=Number(r.debit||0),credit=Number(r.credit||0);balance+=debit-credit;totalDebit+=debit;totalCredit+=credit;return '<tr><td>'+esc(r.posting_date)+'</td><td class="lrd-voucher">'+esc(r.voucher_no)+'</td><td>'+esc(r.against_account)+'</td><td class="lrd-remarks">'+esc(r.remarks)+'</td><td>'+amount(debit)+'</td><td>'+amount(credit)+'</td><td>'+fmt(balance)+'</td></tr>'}).join('');
    table.innerHTML='<thead><tr><th>Date</th><th>Voucher No</th><th>Against Account</th><th>Remarks</th><th>Debit</th><th>Credit</th><th>Balance</th></tr></thead><tbody>'+openingRow+(body||'<tr><td colspan="7" class="lrd-empty">No ledger transactions found for these filters.</td></tr>')+'<tr class="lrd-total"><td colspan="4">Total / Closing Balance</td><td>'+fmt(totalDebit)+'</td><td>'+fmt(totalCredit)+'</td><td>'+fmt(balance)+'</td></tr></tbody>';
    $('#lrd-summary').textContent=rows.length+' transactions · Closing '+fmt(balance);
  }
  function load(){
    $('#lrd-loading').style.display='block';$('#lrd-error').style.display='none';const company=companyControl?companyControl.get_value():'',account=accountControl?accountControl.get_value():'',partyType=$('#lrd-party-type').value,party=partyControl?partyControl.get_value():'';
    frappe.call({method:'ledger_report_api',args:{company:company,from_date:$('#lrd-from').value,to_date:$('#lrd-to').value,account:account,party_type:partyType,party:party},callback:r=>{render(r.message||{});$('#lrd-loading').style.display='none'},error:e=>{$('#lrd-loading').style.display='none';$('#lrd-error').style.display='block';$('#lrd-error').textContent=(e&&e.message)||'Could not load ledger report.'}})
  }
  function printReport(){const table=$('#lrd-table');if(!table)return;const win=window.open('','_blank','width=1400,height=900');if(!win){frappe.msgprint('Please allow pop-ups to print this report.');return}const company=companyControl?companyControl.get_value():'',party=partyControl?partyControl.get_value():'',context=(company?esc(company)+' · ':'')+'From '+esc($('#lrd-from').value)+' to '+esc($('#lrd-to').value)+' · '+esc($('#lrd-party-type').value||'All Parties')+(party?' · '+esc(party):'');win.document.write('<!doctype html><html><head><title>Ledger Report</title><style>@page{size:landscape;margin:10mm}*{box-sizing:border-box}body{font-family:Arial,sans-serif;color:#1e293b;margin:0}.head{display:flex;justify-content:space-between;align-items:flex-end;margin-bottom:10px}.head h1{font-size:18px;margin:0}.head div{font-size:10px;color:#64748b}table{width:100%;border-collapse:collapse;table-layout:fixed;font-size:8px}th,td{padding:4px 5px;border:1px solid #dbe2ea;overflow:hidden;text-overflow:ellipsis}th{background:#e2e8f0}th:nth-child(1){width:10%}th:nth-child(2){width:17%}th:nth-child(3){width:18%}th:nth-child(4){width:28%}th:nth-child(n+5){width:9%;text-align:right}td:nth-child(n+5){text-align:right}.lrd-opening td{background:#eff6ff;font-weight:700}.lrd-total td{background:#f1f5f9;font-weight:700}</style></head><body><div class="head"><h1>Ledger Report</h1><div>'+context+'</div></div>'+table.outerHTML+'</body></html>');win.document.close();win.focus();setTimeout(function(){win.print();win.close()},300)}
  defaults();const qs=params();companyControl=makeLink($('#lrd-company-control'),'Company','Search Company');accountControl=makeLink($('#lrd-account-control'),'Account','Search Account');makePartyLink();setTimeout(function(){if(companyControl)companyControl.set_value(qs.get('company')||userCompany());if(qs.get('account')&&accountControl)accountControl.set_value(qs.get('account'));if(qs.get('party')&&partyControl)partyControl.set_value(qs.get('party'));load()},100);$('#lrd-load').addEventListener('click',load);$('#lrd-print').addEventListener('click',printReport);['#lrd-from','#lrd-to'].forEach(s=>$(s).addEventListener('change',load));$('#lrd-party-type').addEventListener('change',function(){makePartyLink()});
})();
